data_as_directories = TRUE
data = "D:/OneDrive - hawaii.edu/Documents/Projects/Packages/LandCover/Examples/dat1.xlsx"
shp_reg_directory = NULL
shp_reg_layer = NULL
shp_app_directory = NULL
shp_app_layer = NULL
convertFromUTM = FALSE
dat_sample = NULL
landcover_varname = 'landcover'
reg_formula = ET ~ elevation + temp
landcover_invasive = 1
landcover_susceptible = 2
dep_varname = 'LC'
x_coords_varname = 'x'
y_coords_varname = 'y'
val_adjustment = NULL
spread_rate = 0.05
birdcell = 0
simlength = 15
simulation_count = 100
dep_var_modifier = 0.8
covar_adjustment = list('temp', 0)
num_cores = 5
