data_as_directories = TRUE
data = "D:/OneDrive - hawaii.edu/Documents/Projects/Packages/LandCover/Examples/dat1.xlsx"
landcover_varname     = 'landcover'
landcover_invasive    = 1
landcover_susceptible = 2
reg_formula           = ET ~ elevation + temp
x_coords_varname      = 'x'
y_coords_varname      = 'y'
spread_rate           = 0.05
birdcell              = 0
simlength             = 15
simulation_count      = 100
dep_var_modifier      = 0.80
shp_reg = NULL
shp_app = NULL
convertFromUTM = FALSE
dat_sample = NULL
simulation_count = 1000
num_cores = 5
covar_adjustment = NULL
